#ifndef _SYNCBREEZE_H_
#define _SYNCBREEZE_H_

#include <Windows.h>
#include "syncbreeze_struct.h"

int syncbreeze_init();

extern type_SCA_InitSystem SCA_InitSystem;
extern type_SCA_NetTransport_SCA_NetTransport SCA_NetTransport_SCA_NetTransport;
extern type_SCA_NetTransport_Connect SCA_NetTransport_Connect;
extern type_SCA_NetTransport_DeleteFileA SCA_NetTransport_DeleteFileA;
extern type_SCA_NetTransport_UploadFile SCA_NetTransport_UploadFile;
extern type_SCA_NetTransport_DownloadFile SCA_NetTransport_DownloadFile;
extern type_SCA_NetTransport_Destroy SCA_NetTransport_Destroy;

extern type_SCA_SyncBreezeInterface_SCA_SyncBreezeInterface SCA_SyncBreezeInterface_SCA_SyncBreezeInterface;
extern type_SCA_SyncBreezeClient_SCA_SyncBreezeClient SCA_SyncBreezeClient_SCA_SyncBreezeClient;
extern type_SCA_SyncBreezeClient_Connect SCA_SyncBreezeClient_Connect;
extern type_SCA_SyncBreezeInterface_Login SCA_SyncBreezeInterface_Login;
extern type_SCA_SyncBreezeInterface_AddSpaceMonitor SCA_SyncBreezeInterface_AddSpaceMonitor;
extern type_SCA_SyncBreezeClient_LoginEx2 SCA_SyncBreezeClient_LoginEx2;
extern type_SCA_SyncBreezeClient_Destroy SCA_SyncBreezeClient_Destroy;

extern type_SCA_SpaceMon_SCA_SpaceMon SCA_SpaceMon_SCA_SpaceMon;
extern type_SCA_SpaceMonAction_SCA_SpaceMonAction SCA_SpaceMonAction_SCA_SpaceMonAction;
extern type_SCA_SyncBreezeClient_GetSpaceMonitorListObj SCA_SyncBreezeClient_GetSpaceMonitorListObj;
extern type_SCA_SyncBreezeClient_DeleteSpaceMonitor SCA_SyncBreezeClient_DeleteSpaceMonitor;

extern type_SCA_ConfigObj_Load SCA_ConfigObj_Load;
extern type_SCA_ConfigObj_SCA_ConfigObj SCA_ConfigObj_SCA_ConfigObj;
extern type_SCA_ConfigObj_Show SCA_ConfigObj_Show;
extern type_SCA_ConfigObj_GetField_cci SCA_ConfigObj_GetField_cci;

extern PVOID SCA_ListItem_SCA_SpaceMonAction_vftable;

#endif
